#!/usr/bin/env bash
# Vundle
## Make bundle directory
mkdir -p ${HOME}/.vim/bundle ${HOME}/.vim/completion

## Install or update vundle repo
VUNDLE_DIR="${HOME}/.vim/bundle/vundle/"
if [ -d "${VUNDLE_DIR}/.git" ]; then
	CWD="$(pwd)"
	cd "${VUNDLE_DIR}"
	git pull origin master
	cd "${CWD}"
else
	git clone https://github.com/gmarik/vundle.git "${VUNDLE_DIR}"
fi

## Install vundle plugins
echo | echo | vim +PluginInstall! +qall &>/dev/null

# Setup tmux
## start a server but don't attach to it
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux start-server

## create a new session but don't attach to it either
tmux new-session -d
sleep 1

## install the plugins
~/.tmux/plugins/tpm/bin/install_plugins

## killing the server is not required, I guess
tmux kill-server

## bash profile
rm ~/.bash_profile
ln -s ~/.bashrc ~/.bash_profile
