#!/usr/bin/env bash

indent() {
    "$@" 2>&1 | sed 's/^/    /'
}

mkdir -p ${HOME}/.vim/bundle ${HOME}/.vim/completion

## Install or update vundle repo
VUNDLE_DIR="${HOME}/.vim/bundle/vundle/"
if [ -d "${VUNDLE_DIR}/.git" ]; then
	echo "Updating vundle..."
	CWD="$(pwd)"
	cd "${VUNDLE_DIR}"
	indent git pull origin master
	cd "${CWD}"
else
	echo "Installing vundle..."
	indent git clone https://github.com/gmarik/vundle.git "${VUNDLE_DIR}"
fi

## Install vundle plugins
echo "Installing vim plugins..."
indent echo | echo | vim +PluginInstall! +qall &> /dev/null

# Setup tmux - there is no mechanic for updating
if [ ! -d "${HOME}/.tmux/plugins/tpm" ]; then
	echo "Installing tmux plugin manager..."
	indent git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi
tmux start-server
tmux new-session -d

## install tmux plugins
echo "Installing tmux plugins..."
sleep 1
indent "${HOME}/.tmux/plugins/tpm/bin/install_plugins"

## bash profile
echo "Setting bash profile symlink..."
rm ~/.bash_profile
ln -s ~/.bashrc ~/.bash_profile
echo "fin"
